#define		ATOMATRIX_VERSION_SERIAL	20040120
#define		ATOMATRIX_VERSION_REVISION	7
#define		ATOMATRIX_VERSION_SERIAL_Q	"20040120"
#define		ATOMATRIX_VERSION_REVISION_Q	"7"

#if ATOMATRIX_VERSION_REVSION == 0
# define	ATOMATRIX		ATOMATRIX_VERSION_SERIAL_Q
# define	ATOMATRIX_VERSION_Q	ATOMATRIX_VERSION_SERIAL_Q
#else
# define	ATOMATRIX		ATOMATRIX_VERSION_SERIAL_Q "." ATOMATRIX_VERSION_REVISION_Q
# define	ATOMATRIX_VERSION	ATOMATRIX_VERSION_SERIAL.ATOMATRIX_VERSION_REVISION
# define	ATOMATRIX_VERSION_Q	ATOMATRIX_VERSION_SERIAL_Q "." ATOMATRIX_VERSION_REVISION_Q
#endif
