#define		ATOMATRIX_VERSION_SERIAL	20030322
#define		ATOMATRIX_VERSION_REVISION	0
#define		ATOMATRIX_VERSION_SERIAL_Q	"20030322"
#define		ATOMATRIX_VERSION_REVISION_Q	"0"

#if ATOMATRIX_VERSION_REVSION == 0
# define	ATOMATRIX		ATOMATRIX_VERSION_SERIAL_Q
# define	ATOMATRIX_VERSION_Q	ATOMATRIX_VERSION_SERIAL_Q
#else
# define	ATOMATRIX		ATOMATRIX_VERSION_SERIAL_Q "." ATOMATRIX_VERSION_REVISION_Q
# define	ATOMATRIX_VERSION	ATOMATRIX_VERSION_SERIAL.ATOMATRIX_VERSION_REVISION
# define	ATOMATRIX_VERSION_Q	ATOMATRIX_VERSION_SERIAL_Q "." ATOMATRIX_VERSION_REVISION_Q
#endif
